# SPDX-FileCopyrightText: 2021 Sebastian Garcia <sebastian.garcia@agents.fel.cvut.cz>
# SPDX-License-Identifier: GPL-2.0-only
class Constants:
    LOADED_TI_FILES = "loaded_TI_files_number"
    TI_FILES_INFO = "TI_files_info"
    CURRENT_TIMEWINDOW = "current_timewindow"
    # all keys starting with IoC_* are used for storing IoCs read from
    # online and offline TI feeds
    IOC_IPS = "IoC_ips"
    IOC_DOMAINS = "IoC_domains"
    IOC_IP_RANGES = "IoC_ip_ranges"
    IOC_ASN = "IoC_ASNs"
    IOC_JA3 = "IoC_JA3"
    IOC_JARM = "IoC_JARM"
    IOC_SSL = "IoC_SSL"
    LABELED_AS_MALICIOUS = "labeled_as_malicious"
    # used to cache url info by the virustotal module only
    VT_CACHED_URL_INFO = "virustotal_cached_url_info"
    # used for Kalipso
    DOMAINS_INFO = "DomainsInfo"
    IPS_INFO = "IPsInfo"
    PROCESSED_FLOWS_BY_PROFILER = "processed_flows_by_profiler_so_far"
    FLOWS_CAUSING_EVIDENCE = "flows_causing_evidence"
    PROCESSED_EVIDENCE = "processed_evidence"
    NUMBER_OF_EVIDENCE = "number_of_evidence"
    WHITELISTED_EVIDENCE = "whitelisted_evidence"
    SRCIPS_SEEN_IN_CONN_LOG = "srcips_seen_in_connlog"
    PASSIVE_DNS = "passiveDNS"
    # called for every ip in kalipso timeline
    DNS_RESOLUTION = "DNSresolution"
    DOMAINS_RESOLVED = "DomainsResolved"
    CACHED_ASN = "cached_asn"
    PIDS = "PIDs"
    MAC = "MAC"
    MODIFIED_TIMEWINDOWS = "ModifiedTW"
    ACCUMULATED_THREAT_LEVELS = "accumulated_threat_levels"
    TRANCO_WHITELISTED_DOMAINS = "tranco_whitelisted_domains"
    WHITELIST = "whitelist"
    GROWING_ZEEK_DIR = "growing_zeek_dir"
    DHCP_SERVERS = "DHCP_servers"
    LABELS = "labels"
    MSGS_PUBLISHED_AT_RUNTIME = "msgs_published_at_runtime"
    ZEEK_FILES = "zeekfiles"
    DEFAULT_GATEWAY = "default_gateway"
    IS_CYST_ENABLED = "is_cyst_enabled"
    LOCAL_NETWORK = "local_network"
    ZEEK_PATH = "zeek_path"
    P2P_REPORTS = "p2p_reports"
    ORGANIZATIONS_PORTS = "organization_port"
    SLIPS_START_TIME = "slips_start_time"
    USED_FTP_PORTS = "used_ftp_ports"
    SLIPS_INTERNAL_TIME = "slips_internal_time"
    IS_RUNNING_AS_AP = "is_slips_running_as_an_ap"
    WARDEN_INFO = "Warden"
    MODE = "mode"
    ANALYSIS = "analysis"
    LOGGED_CONNECTION_ERR = "logged_connection_error"
    P2P_RECEIVED_BLAME_REPORTS = "p2p-received-blame-reports"
    MULTICAST_ADDRESS = "multiAddress"
    PORT_INFO = "portinfo"
    REQUESTED_DHCP_ADDRS = "requested_DHCP_addrs"
    REDIS_USED_PORT = "port"
    # used in the web interface
    BLOCKED_PROFILES_AND_TWS = "BlockedProfTW"
    BLOCKED_IPS = "blocked_ips"
    PROFILES = "profiles"
    NUMBER_OF_ALERTS = "number_of_alerts"
    KNOWN_FP_MD5_HASHES = "known_fps"
    WILL_SLIPS_HAVE_MORE_FLOWS = "will_slips_have_more_flows"
    SUBS_WHO_PROCESSED_MSG = "number_of_subscribers_who_processed_this_msg"
    FLOWS_ANALYZED_BY_ALL_MODULES_PER_MIN = "flows_analyzed_per_minute"
    MODULES_FLOWS_PER_SECOND = "modules_processed_flows_per_second"
    THROUGHPUT_FPS = "throughput_fps"
    THROUGHPUT_COUNTER = "throughput_counter"
    LINE_PROCESSORS = "line_processors"
    ALERTS = "alerts"
    MAX_THREAT_LEVEL = "max_threat_level"
    THREAT_LEVEL = "threat_level"
    RECONNECTIONS = "Reconnections"
    HOST_IP_SCAN_PATTERN = "host_ip_*"
    WARDEN_POLL = "poll"
    ANALYSIS_ZEEK_DIR = "zeek_dir"
    ANALYSIS_NAME = "name"
    ANALYSIS_COMMIT = "commit"
    ANALYSIS_ZEEK_VERSION = "zeek_version"
    ANALYSIS_BRANCH = "branch"
    ANALYSIS_INPUT_TYPE = "input_type"
    ANALYSIS_INTERFACE = "interface"
    ANALYSIS_OUTPUT_DIR = "output_dir"
    ANALYSIS_FILE_START = "file_start"
    ANALYSIS_TOTAL_FLOWS = "total_flows"
    USED_SOFTWARE = "used_software"
    FIRST_USER_AGENT = "first user-agent"
    USER_AGENTS_COUNT = "user_agents_count"
    PAST_USER_AGENTS = "past_user_agents"
    DHCP = "dhcp"
    MODULES_LABELS = "modules_labels"
    GATEWAY = "gateway"
    IPV4 = "IPv4"
    IPV6 = "IPv6"
    MAC_VENDOR = "MAC_vendor"
    HOST_NAME = "host_name"
    STARTTIME = "starttime"
    DURATION = "duration"
    CONFIDENCE = "confidence"
    CONNECTED_PEERS = "connected_peers"
    PEER_TRUST = "peer_trust"
    P2P_TRUST_SET = "peers_strust"
    P2P_PEER_INFO_HASH = "peer_info"
    FIDES_CACHE_KEY = "fides_cache"
    FIDES_CACHE_CREATED_SECONDS = "created_seconds"


class Channels:
    NEW_ALERT = "new_alert"
    EVIDENCE_ADDED = "evidence_added"
    GIVE_TI = "get_modified_profiles_since"
    NEW_ZEEK_FIELDS_LINE = "new_zeek_fields_line"
    CONTROL_CHANNEL = "control_channel"
