name: 'Install missing Python dependencies'
description: 'Installs missing Python packages listed in install/requirements.txt'
runs:
  using: "composite"
  steps:
    - name: Install missing pip packages
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r install/requirements.txt
