import os
from pathlib import Path

from slips_files.common.parsers.config_parser import ConfigParser

DATABASES_DIRNAME = "databases"
ALERTS_DIRNAME = "alerts"
REDIS_DIRNAME = "redis"

PERFORMANCE_PLOTS_DIRNAME = "performance_plots"
PERFORMANCE_CSV_DIRNAME = "csv"


def get_databases_dir_path_inside_output_dir(parent_dir: str) -> str:
    """
    any db generated by slips and should be overwritten per run,
    goes in this dir
    return the databses/ path inside the parent output dir
    e.g output_123/databses/
    :param parent_dir: parent output dir. the main one given to slips with -o
    """
    databases_dir = os.path.join(parent_dir or ".", DATABASES_DIRNAME)
    os.makedirs(databases_dir, exist_ok=True)
    return databases_dir


def get_redis_dir_path_inside_output_dir(parent_dir: str) -> str:
    """
    any redis logs generated by slips and should be overwritten per run,
    goes in this dir
    :param parent_dir: parent output dir. the main one given to slips with -o
    """
    redis_dir = os.path.join(parent_dir or ".", REDIS_DIRNAME)
    os.makedirs(redis_dir, exist_ok=True)
    return redis_dir


def get_this_db_path_inside_output_dir(parent_dir: str, filename: str) -> str:
    return os.path.join(
        get_databases_dir_path_inside_output_dir(parent_dir), filename
    )


def get_permanent_dir() -> str:
    """
    Return the root directory for persistent runtime data.

    Returns:
        Relative path where runtime-generated data that must persist
        across different Slips runs is stored.
    """
    conf = ConfigParser()
    permanent_dir = conf.permanent_dir()

    # make sure it's inside slips root dir
    permanent_dir = os.path.join(os.getcwd(), permanent_dir)
    Path(permanent_dir).mkdir(parents=True, exist_ok=True)

    return permanent_dir


def get_this_filepath_inside_permanent_dir(filename: str) -> str:
    """use this func if you plan to persist your filename across runs."""
    return os.path.join(get_permanent_dir(), filename)


def get_alerts_path_inside_output_dir(parent_dir: str) -> str:
    return os.path.join(parent_dir, ALERTS_DIRNAME)


def get_redis_logs_path_inside_output_dir(
    parent_dir: str, logfile: str
) -> str:
    return os.path.join(
        get_redis_dir_path_inside_output_dir(parent_dir), logfile
    )


def get_performance_plots_dir(parent_dir: str) -> str:
    """output/performance_plots/"""
    return os.path.join(parent_dir or "", PERFORMANCE_PLOTS_DIRNAME)


def get_performance_csv_dir(parent_dir: str) -> str:
    """
    csv files used for generating the plots go into
    output/performance_plots/csv/
    This func returns that path
    """
    return os.path.join(
        get_performance_plots_dir(parent_dir), PERFORMANCE_CSV_DIRNAME
    )


def get_performance_csv_path(output_dir: str, filename: str) -> str:
    """returns the full path to the given filename inside the csv dir"""
    return os.path.join(get_performance_csv_dir(output_dir), filename)
