import subprocess

from slips_files.common.abstracts.iinput_reader import IInputReader


class NfdumpReader(IInputReader):
    name = "NfdumpReader"
    description = "Reads nfdump files"

    def init(self): ...

    def read(self, given_path):
        """returns the number of lines read"""
        command = f"nfdump -b -N -o csv -q -r {given_path}"
        result = subprocess.run(command.split(), stdout=subprocess.PIPE)
        nfdump_output = result.stdout.decode("utf-8")
        lines = self.read_nfdump_output(nfdump_output)
        return lines

    def read_nfdump_output(self, nfdump_output) -> int:
        """
        A binary file generated by nfcapd can be read by nfdump.
        The task for this function is to send nfdump output line by line to
        profiler.py for processing

        Returns the number rof processed flows
        """
        if not nfdump_output:
            # The nfdump command returned nothing
            self.print("Error reading nfdump output ", 1, 3)
            return 0

        self.total_flows = len(nfdump_output.splitlines())
        self.db.set_input_metadata({"total_flows": self.total_flows})

        for nfdump_line in nfdump_output.splitlines():
            # this line is taken from stdout we need to remove whitespaces
            nfdump_line.replace(" ", "")
            line = {"type": "nfdump", "data": nfdump_line}
            self.give_profiler(line)
            if self.testing:
                break

        return self.total_flows
