# SPDX-FileCopyrightText: 2021 Sebastian Garcia <sebastian.garcia@agents.fel.cvut.cz>
# SPDX-License-Identifier: GPL-2.0-only

import subprocess

from slips_files.common.abstracts.iinput_handler import IInputHandler


class NfdumpInput(IInputHandler):
    def __init__(self, input_process):
        super().__init__(input_process)
        self.db = self.input.db

    def read_nfdump_output(self) -> int:
        """
        A binary file generated by nfcapd can be read by nfdump.
        The task for this function is to send nfdump output line by line to
        iperformance_profiler.py for processing
        """
        if not self.nfdump_output:
            # The nfdump command returned nothing
            self.input.print("Error reading nfdump output ", 1, 3)
        else:
            self.input.total_flows = len(self.nfdump_output.splitlines())
            self.db.set_input_metadata({"total_flows": self.input.total_flows})
            for nfdump_line in self.nfdump_output.splitlines():
                # this line is taken from stdout we need to remove whitespaces
                nfdump_line.replace(" ", "")
                line = {"type": "nfdump", "data": nfdump_line}
                self.input.give_profiler(line)
                if self.input.testing:
                    break

        return self.input.total_flows

    def run(self):
        command = f"nfdump -b -N -o csv -q -r {self.input.given_path}"
        # Execute command
        result = subprocess.run(command.split(), stdout=subprocess.PIPE)
        # Get command output
        self.nfdump_output = result.stdout.decode("utf-8")
        self.input.lines = self.read_nfdump_output()
        self.input.print_lines_read()
        self.input.mark_self_as_done_processing()
        return True

    def shutdown_gracefully(self):
        self.input.mark_self_as_done_processing()
        return True
