# SPDX-FileCopyrightText: 2021 Sebastian Garcia <sebastian.garcia@agents.fel.cvut.cz>
# SPDX-License-Identifier: GPL-2.0-only

import subprocess

from slips_files.common.abstracts.iinput_handler import IInputHandler
from slips_files.common.slips_utils import utils


class NfdumpInput(IInputHandler):
    def __init__(self, input_process):
        super().__init__(input_process)
        self.db = self.input.db

    def read_nfdump_output(self) -> int:
        """
        A binary file generated by nfcapd can be read by nfdump.
        The task for this function is to send nfdump output line by line to
        iperformance_profiler.py for processing
        """
        if not self.nfdump_output:
            # The nfdump command returned nothing
            self.input.print("Error reading nfdump output ", 1, 3)
        else:
            self.input.total_flows = len(self.nfdump_output.splitlines())
            self.db.set_input_metadata({"total_flows": self.input.total_flows})
            for nfdump_line in self.nfdump_output.splitlines():
                # this line is taken from stdout we need to remove whitespaces
                nfdump_line.replace(" ", "")
                line = {"type": "nfdump", "data": nfdump_line}
                self.input.give_profiler(line)
                if self.input.testing:
                    break

        return self.input.total_flows

    def run(self):
        safe_path = utils.validate_safe_path(
            self.input.given_path, must_exist=True
        )
        # The default CSV schema changed in nfdump 1.7. Request the legacy
        # column order explicitly, which is also supported by nfdump 1.6.
        output_format = (
            "fmt:%ts,%te,%td,%sa,%da,%sp,%dp,%pr,%flg,%fwd,%stos,"
            "%ipkt,%ibyt,%opkt,%obyt,%in,%out,%sas,%das,%smk,%dmk,%dtos,%dir"
        )
        command = [
            "nfdump",
            "-b",
            "-N",
            "-6",
            "-o",
            output_format,
            "-q",
            "-r",
            safe_path,
        ]
        # Execute command
        result = subprocess.run(command, stdout=subprocess.PIPE)
        # Get command output
        self.nfdump_output = result.stdout.decode("utf-8")
        self.input.lines = self.read_nfdump_output()
        return True

    def shutdown_gracefully(self):
        self.input.mark_self_as_done_processing()
        return True
